import { writeFileSync } from 'node:fs';
import {
  HDNodeWallet,
  Interface,
  TypedDataEncoder,
  concat,
  hashAuthorization,
  toBeHex,
} from 'ethers';

const wallet = HDNodeWallet.fromPhrase(
  'test test test test test test test test test test test junk',
);
const token = '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9';
const paymaster = '0x888888888888Ec68A58AB8094Cc1AD20Ba3D2402';
const delegate = '0xe6Cae83BdE06E4c305530e199D7217f42808555B';
const entryPoint = '0x4337084D9E255Ff0702461CF8895CE9E3b5Ff108';
const tokenAbi = new Interface([
  'function approve(address,uint256)',
  'function transfer(address,uint256)',
]);
const accountAbi = new Interface([
  'function executeBatch((address target,uint256 value,bytes data)[] calls)',
]);
const calls = [
  { to: token, data: tokenAbi.encodeFunctionData('approve', [paymaster, 100000]) },
  {
    to: token,
    data: tokenAbi.encodeFunctionData('transfer', [
      '0x1111111111111111111111111111111111111111',
      1000000,
    ]),
  },
];
const authorization = { chainId: 42161, address: delegate, nonce: 0 };
const authHash = hashAuthorization(authorization);
const authSignature = wallet.signingKey.sign(authHash);
const op = {
  sender: wallet.address,
  nonce: '0x0',
  factory: '0x7702',
  factoryData: '0x',
  callData: accountAbi.encodeFunctionData('executeBatch', [calls.map((c) => [c.to, 0, c.data])]),
  callGasLimit: '0x249f0',
  verificationGasLimit: '0x3d090',
  preVerificationGas: '0x13880',
  maxFeePerGas: '0x2faf080',
  maxPriorityFeePerGas: '0x186a0',
  paymaster,
  paymasterVerificationGasLimit: '0x186a0',
  paymasterPostOpGasLimit: '0xc350',
  paymasterData: concat([
    '0x0300',
    toBeHex(1800000000, 6),
    toBeHex(0, 6),
    token,
    toBeHex(50000, 16),
    toBeHex(3000000000, 32),
    toBeHex(100000, 16),
    wallet.address,
    toBeHex(1, 65),
  ]),
  signature: '0x',
  eip7702Auth: {
    chainId: '0xa4b1',
    address: delegate,
    nonce: '0x0',
    yParity: toBeHex(authSignature.yParity),
    r: authSignature.r,
    s: authSignature.s,
  },
};
const types = {
  PackedUserOperation: [
    ['sender', 'address'],
    ['nonce', 'uint256'],
    ['initCode', 'bytes'],
    ['callData', 'bytes'],
    ['accountGasLimits', 'bytes32'],
    ['preVerificationGas', 'uint256'],
    ['gasFees', 'bytes32'],
    ['paymasterAndData', 'bytes'],
  ].map(([name, type]) => ({ name, type })),
};
const packed = {
  sender: op.sender,
  nonce: op.nonce,
  initCode: delegate,
  callData: op.callData,
  accountGasLimits: concat([toBeHex(op.verificationGasLimit, 16), toBeHex(op.callGasLimit, 16)]),
  preVerificationGas: op.preVerificationGas,
  gasFees: concat([toBeHex(op.maxPriorityFeePerGas, 16), toBeHex(op.maxFeePerGas, 16)]),
  paymasterAndData: concat([
    paymaster,
    toBeHex(op.paymasterVerificationGasLimit, 16),
    toBeHex(op.paymasterPostOpGasLimit, 16),
    op.paymasterData,
  ]),
};
const hash = TypedDataEncoder.hash(
  { name: 'ERC4337', version: '1', chainId: 42161, verifyingContract: entryPoint },
  types,
  packed,
);
const signature = wallet.signingKey.sign(hash).serialized;
writeFileSync(
  new URL('../../src/modules/usdt/fixtures/eip7702-vectors.json', import.meta.url),
  JSON.stringify(
    {
      source:
        'ethers@6.17.0; EntryPoint v0.8 / Simple7702Account; generated by tests/usdt-fork/vectors.mjs',
      address: wallet.address,
      calls,
      operation: op,
      userOperationHash: hash,
      signature,
      authorizationHash: authHash,
    },
    null,
    2,
  ) + '\n',
);
