// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.bitkitcore;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.ConcurrentHashMap
import kotlin.coroutines.resume
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.suspendCancellableCoroutine

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_bitkitcore_rustbuffer_alloc(size, status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: Int, len: Int, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity
            buf.len = len
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_bitkitcore_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getInt(0))
        value.writeField("len", pointer.getInt(4))
        value.writeField("data", pointer.getPointer(8))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: RustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == 0.toByte()
    }

    fun isError(): Boolean {
        return code == 1.toByte()
    }

    fun isPanic(): Boolean {
        return code == 2.toByte()
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    checkCallStatus(errorHandler, status)
    return return_value
}

// Check RustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> checkCallStatus(errorHandler: CallStatusErrorHandler<E>, status: RustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// IntegerType that matches Rust's `usize` / C's `size_t`
public class USize(value: Long = 0) : IntegerType(Native.SIZE_T_SIZE, value, true) {
    // This is needed to fill in the gaps of IntegerType's implementation of Number for Kotlin.
    override fun toByte() = toInt().toByte()
    // Needed until https://youtrack.jetbrains.com/issue/KT-47902 is fixed.
    @Deprecated("`toInt().toChar()` is deprecated")
    override fun toChar() = toInt().toChar()
    override fun toShort() = toInt().toShort()

    fun writeToBuffer(buf: ByteBuffer) {
        // Make sure we always write usize integers using native byte-order, since they may be
        // casted to pointer values
        buf.order(ByteOrder.nativeOrder())
        try {
            when (Native.SIZE_T_SIZE) {
                4 -> buf.putInt(toInt())
                8 -> buf.putLong(toLong())
                else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
            }
        } finally {
            buf.order(ByteOrder.BIG_ENDIAN)
        }
    }

    companion object {
        val size: Int
            get() = Native.SIZE_T_SIZE

        fun readFromBuffer(buf: ByteBuffer) : USize {
            // Make sure we always read usize integers using native byte-order, since they may be
            // casted from pointer values
            buf.order(ByteOrder.nativeOrder())
            try {
                return when (Native.SIZE_T_SIZE) {
                    4 -> USize(buf.getInt().toLong())
                    8 -> USize(buf.getLong())
                    else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
                }
            } finally {
                buf.order(ByteOrder.BIG_ENDIAN)
            }
        }
    }
}


// Map handles to objects
//
// This is used when the Rust code expects an opaque pointer to represent some foreign object.
// Normally we would pass a pointer to the object, but JNA doesn't support getting a pointer from an
// object reference , nor does it support leaking a reference to Rust.
//
// Instead, this class maps USize values to objects so that we can pass a pointer-sized type to
// Rust when it needs an opaque pointer.
//
// TODO: refactor callbacks to use this class
internal class UniFfiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<USize, T>()
    // Use AtomicInteger for our counter, since we may be on a 32-bit system.  4 billion possible
    // values seems like enough. If somehow we generate 4 billion handles, then this will wrap
    // around back to zero and we can assume the first handle generated will have been dropped by
    // then.
    private val counter = java.util.concurrent.atomic.AtomicInteger(0)

    val size: Int
        get() = map.size

    fun insert(obj: T): USize {
        val handle = USize(counter.getAndAdd(1).toLong())
        map.put(handle, obj)
        return handle
    }

    fun get(handle: USize): T? {
        return map.get(handle)
    }

    fun remove(handle: USize): T? {
        return map.remove(handle)
    }
}

// FFI type for Rust future continuations
internal interface UniFffiRustFutureContinuationCallbackType : com.sun.jna.Callback {
    fun callback(continuationHandle: USize, pollResult: Short);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "bitkitcore"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "bitkitcore")
            .also { lib: _UniFFILib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                uniffiRustFutureContinuationCallback.register(lib)
                }
        }
    }

    fun uniffi_bitkitcore_fn_func_decode(`invoice`: RustBuffer.ByValue,
    ): Pointer
    fun uniffi_bitkitcore_fn_func_get_lnurl_invoice(`address`: RustBuffer.ByValue,`amountSatoshis`: Long,
    ): Pointer
    fun uniffi_bitkitcore_fn_func_validate_bitcoin_address(`address`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_bitkitcore_rustbuffer_alloc(`size`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_bitkitcore_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_bitkitcore_rustbuffer_free(`buf`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun ffi_bitkitcore_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_bitkitcore_rust_future_continuation_callback_set(`callback`: UniFffiRustFutureContinuationCallbackType,
    ): Unit
    fun ffi_bitkitcore_rust_future_poll_u8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_u8(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_u8(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_u8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_bitkitcore_rust_future_poll_i8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_i8(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_i8(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_i8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_bitkitcore_rust_future_poll_u16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_u16(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_u16(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_u16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_bitkitcore_rust_future_poll_i16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_i16(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_i16(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_i16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_bitkitcore_rust_future_poll_u32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_u32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_u32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_u32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_bitkitcore_rust_future_poll_i32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_i32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_i32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_i32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_bitkitcore_rust_future_poll_u64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_u64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_u64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_u64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_bitkitcore_rust_future_poll_i64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_i64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_i64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_i64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_bitkitcore_rust_future_poll_f32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_f32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_f32(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_f32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Float
    fun ffi_bitkitcore_rust_future_poll_f64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_f64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_f64(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_f64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Double
    fun ffi_bitkitcore_rust_future_poll_pointer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_pointer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Pointer
    fun ffi_bitkitcore_rust_future_poll_rust_buffer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_rust_buffer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_bitkitcore_rust_future_poll_void(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_bitkitcore_rust_future_cancel_void(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_free_void(`handle`: Pointer,
    ): Unit
    fun ffi_bitkitcore_rust_future_complete_void(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_bitkitcore_checksum_func_decode(
    ): Short
    fun uniffi_bitkitcore_checksum_func_get_lnurl_invoice(
    ): Short
    fun uniffi_bitkitcore_checksum_func_validate_bitcoin_address(
    ): Short
    fun ffi_bitkitcore_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: _UniFFILib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_bitkitcore_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: _UniFFILib) {
    if (lib.uniffi_bitkitcore_checksum_func_decode() != 21596.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bitkitcore_checksum_func_get_lnurl_invoice() != 35835.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_bitkitcore_checksum_func_validate_bitcoin_address() != 30728.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support
// Async return type handlers

internal const val UNIFFI_RUST_FUTURE_POLL_READY = 0.toShort()
internal const val UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1.toShort()

internal val uniffiContinuationHandleMap = UniFfiHandleMap<CancellableContinuation<Short>>()

// FFI type for Rust future continuations
internal object uniffiRustFutureContinuationCallback: UniFffiRustFutureContinuationCallbackType {
    override fun callback(continuationHandle: USize, pollResult: Short) {
        uniffiContinuationHandleMap.remove(continuationHandle)?.resume(pollResult)
    }

    internal fun register(lib: _UniFFILib) {
        lib.ffi_bitkitcore_rust_future_continuation_callback_set(this)
    }
}

internal suspend fun<T, F, E: Exception> uniffiRustCallAsync(
    rustFuture: Pointer,
    pollFunc: (Pointer, USize) -> Unit,
    completeFunc: (Pointer, RustCallStatus) -> F,
    freeFunc: (Pointer) -> Unit,
    liftFunc: (F) -> T,
    errorHandler: CallStatusErrorHandler<E>
): T {
    try {
        do {
            val pollResult = suspendCancellableCoroutine<Short> { continuation ->
                pollFunc(
                    rustFuture,
                    uniffiContinuationHandleMap.insert(continuation)
                )
            }
        } while (pollResult != UNIFFI_RUST_FUTURE_POLL_READY);

        return liftFunc(
            rustCallWithError(errorHandler, { status -> completeFunc(rustFuture, status) })
        )
    } finally {
        freeFunc(rustFuture)
    }
}


// Public interface members begin here.


public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): Int {
        return 4 + value.size
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}




data class LightningInvoice (
    var `paymentHash`: ByteArray, 
    var `amountSatoshis`: ULong, 
    var `timestampSeconds`: ULong, 
    var `expirySeconds`: ULong, 
    var `isExpired`: Boolean, 
    var `description`: String?, 
    var `networkType`: NetworkType, 
    var `payeeNodeId`: ByteArray?
) {
    
    companion object
}

public object FfiConverterTypeLightningInvoice: FfiConverterRustBuffer<LightningInvoice> {
    override fun read(buf: ByteBuffer): LightningInvoice {
        return LightningInvoice(
            FfiConverterByteArray.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterTypeNetworkType.read(buf),
            FfiConverterOptionalByteArray.read(buf),
        )
    }

    override fun allocationSize(value: LightningInvoice) = (
            FfiConverterByteArray.allocationSize(value.`paymentHash`) +
            FfiConverterULong.allocationSize(value.`amountSatoshis`) +
            FfiConverterULong.allocationSize(value.`timestampSeconds`) +
            FfiConverterULong.allocationSize(value.`expirySeconds`) +
            FfiConverterBoolean.allocationSize(value.`isExpired`) +
            FfiConverterOptionalString.allocationSize(value.`description`) +
            FfiConverterTypeNetworkType.allocationSize(value.`networkType`) +
            FfiConverterOptionalByteArray.allocationSize(value.`payeeNodeId`)
    )

    override fun write(value: LightningInvoice, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`paymentHash`, buf)
            FfiConverterULong.write(value.`amountSatoshis`, buf)
            FfiConverterULong.write(value.`timestampSeconds`, buf)
            FfiConverterULong.write(value.`expirySeconds`, buf)
            FfiConverterBoolean.write(value.`isExpired`, buf)
            FfiConverterOptionalString.write(value.`description`, buf)
            FfiConverterTypeNetworkType.write(value.`networkType`, buf)
            FfiConverterOptionalByteArray.write(value.`payeeNodeId`, buf)
    }
}




data class LnurlAddressData (
    var `uri`: String, 
    var `domain`: String, 
    var `username`: String
) {
    
    companion object
}

public object FfiConverterTypeLnurlAddressData: FfiConverterRustBuffer<LnurlAddressData> {
    override fun read(buf: ByteBuffer): LnurlAddressData {
        return LnurlAddressData(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: LnurlAddressData) = (
            FfiConverterString.allocationSize(value.`uri`) +
            FfiConverterString.allocationSize(value.`domain`) +
            FfiConverterString.allocationSize(value.`username`)
    )

    override fun write(value: LnurlAddressData, buf: ByteBuffer) {
            FfiConverterString.write(value.`uri`, buf)
            FfiConverterString.write(value.`domain`, buf)
            FfiConverterString.write(value.`username`, buf)
    }
}




data class LnurlAuthData (
    var `uri`: String, 
    var `tag`: String, 
    var `k1`: String
) {
    
    companion object
}

public object FfiConverterTypeLnurlAuthData: FfiConverterRustBuffer<LnurlAuthData> {
    override fun read(buf: ByteBuffer): LnurlAuthData {
        return LnurlAuthData(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: LnurlAuthData) = (
            FfiConverterString.allocationSize(value.`uri`) +
            FfiConverterString.allocationSize(value.`tag`) +
            FfiConverterString.allocationSize(value.`k1`)
    )

    override fun write(value: LnurlAuthData, buf: ByteBuffer) {
            FfiConverterString.write(value.`uri`, buf)
            FfiConverterString.write(value.`tag`, buf)
            FfiConverterString.write(value.`k1`, buf)
    }
}




data class LnurlChannelData (
    var `uri`: String, 
    var `callback`: String, 
    var `k1`: String, 
    var `tag`: String
) {
    
    companion object
}

public object FfiConverterTypeLnurlChannelData: FfiConverterRustBuffer<LnurlChannelData> {
    override fun read(buf: ByteBuffer): LnurlChannelData {
        return LnurlChannelData(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: LnurlChannelData) = (
            FfiConverterString.allocationSize(value.`uri`) +
            FfiConverterString.allocationSize(value.`callback`) +
            FfiConverterString.allocationSize(value.`k1`) +
            FfiConverterString.allocationSize(value.`tag`)
    )

    override fun write(value: LnurlChannelData, buf: ByteBuffer) {
            FfiConverterString.write(value.`uri`, buf)
            FfiConverterString.write(value.`callback`, buf)
            FfiConverterString.write(value.`k1`, buf)
            FfiConverterString.write(value.`tag`, buf)
    }
}




data class LnurlPayData (
    var `uri`: String, 
    var `callback`: String, 
    var `minSendable`: ULong, 
    var `maxSendable`: ULong, 
    var `metadataStr`: String, 
    var `commentAllowed`: UInt?, 
    var `allowsNostr`: Boolean, 
    var `nostrPubkey`: ByteArray?
) {
    
    companion object
}

public object FfiConverterTypeLnurlPayData: FfiConverterRustBuffer<LnurlPayData> {
    override fun read(buf: ByteBuffer): LnurlPayData {
        return LnurlPayData(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalUInt.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalByteArray.read(buf),
        )
    }

    override fun allocationSize(value: LnurlPayData) = (
            FfiConverterString.allocationSize(value.`uri`) +
            FfiConverterString.allocationSize(value.`callback`) +
            FfiConverterULong.allocationSize(value.`minSendable`) +
            FfiConverterULong.allocationSize(value.`maxSendable`) +
            FfiConverterString.allocationSize(value.`metadataStr`) +
            FfiConverterOptionalUInt.allocationSize(value.`commentAllowed`) +
            FfiConverterBoolean.allocationSize(value.`allowsNostr`) +
            FfiConverterOptionalByteArray.allocationSize(value.`nostrPubkey`)
    )

    override fun write(value: LnurlPayData, buf: ByteBuffer) {
            FfiConverterString.write(value.`uri`, buf)
            FfiConverterString.write(value.`callback`, buf)
            FfiConverterULong.write(value.`minSendable`, buf)
            FfiConverterULong.write(value.`maxSendable`, buf)
            FfiConverterString.write(value.`metadataStr`, buf)
            FfiConverterOptionalUInt.write(value.`commentAllowed`, buf)
            FfiConverterBoolean.write(value.`allowsNostr`, buf)
            FfiConverterOptionalByteArray.write(value.`nostrPubkey`, buf)
    }
}




data class LnurlWithdrawData (
    var `uri`: String, 
    var `callback`: String, 
    var `k1`: String, 
    var `defaultDescription`: String, 
    var `minWithdrawable`: ULong?, 
    var `maxWithdrawable`: ULong, 
    var `tag`: String
) {
    
    companion object
}

public object FfiConverterTypeLnurlWithdrawData: FfiConverterRustBuffer<LnurlWithdrawData> {
    override fun read(buf: ByteBuffer): LnurlWithdrawData {
        return LnurlWithdrawData(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: LnurlWithdrawData) = (
            FfiConverterString.allocationSize(value.`uri`) +
            FfiConverterString.allocationSize(value.`callback`) +
            FfiConverterString.allocationSize(value.`k1`) +
            FfiConverterString.allocationSize(value.`defaultDescription`) +
            FfiConverterOptionalULong.allocationSize(value.`minWithdrawable`) +
            FfiConverterULong.allocationSize(value.`maxWithdrawable`) +
            FfiConverterString.allocationSize(value.`tag`)
    )

    override fun write(value: LnurlWithdrawData, buf: ByteBuffer) {
            FfiConverterString.write(value.`uri`, buf)
            FfiConverterString.write(value.`callback`, buf)
            FfiConverterString.write(value.`k1`, buf)
            FfiConverterString.write(value.`defaultDescription`, buf)
            FfiConverterOptionalULong.write(value.`minWithdrawable`, buf)
            FfiConverterULong.write(value.`maxWithdrawable`, buf)
            FfiConverterString.write(value.`tag`, buf)
    }
}




data class OnChainInvoice (
    var `address`: String, 
    var `amountSatoshis`: ULong, 
    var `label`: String?, 
    var `message`: String?, 
    var `params`: Map<String, String>?
) {
    
    companion object
}

public object FfiConverterTypeOnChainInvoice: FfiConverterRustBuffer<OnChainInvoice> {
    override fun read(buf: ByteBuffer): OnChainInvoice {
        return OnChainInvoice(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalMapStringString.read(buf),
        )
    }

    override fun allocationSize(value: OnChainInvoice) = (
            FfiConverterString.allocationSize(value.`address`) +
            FfiConverterULong.allocationSize(value.`amountSatoshis`) +
            FfiConverterOptionalString.allocationSize(value.`label`) +
            FfiConverterOptionalString.allocationSize(value.`message`) +
            FfiConverterOptionalMapStringString.allocationSize(value.`params`)
    )

    override fun write(value: OnChainInvoice, buf: ByteBuffer) {
            FfiConverterString.write(value.`address`, buf)
            FfiConverterULong.write(value.`amountSatoshis`, buf)
            FfiConverterOptionalString.write(value.`label`, buf)
            FfiConverterOptionalString.write(value.`message`, buf)
            FfiConverterOptionalMapStringString.write(value.`params`, buf)
    }
}




data class PubkyAuth (
    var `data`: String
) {
    
    companion object
}

public object FfiConverterTypePubkyAuth: FfiConverterRustBuffer<PubkyAuth> {
    override fun read(buf: ByteBuffer): PubkyAuth {
        return PubkyAuth(
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PubkyAuth) = (
            FfiConverterString.allocationSize(value.`data`)
    )

    override fun write(value: PubkyAuth, buf: ByteBuffer) {
            FfiConverterString.write(value.`data`, buf)
    }
}




data class ValidationResult (
    var `address`: String, 
    var `network`: NetworkType, 
    var `addressType`: AddressType
) {
    
    companion object
}

public object FfiConverterTypeValidationResult: FfiConverterRustBuffer<ValidationResult> {
    override fun read(buf: ByteBuffer): ValidationResult {
        return ValidationResult(
            FfiConverterString.read(buf),
            FfiConverterTypeNetworkType.read(buf),
            FfiConverterTypeAddressType.read(buf),
        )
    }

    override fun allocationSize(value: ValidationResult) = (
            FfiConverterString.allocationSize(value.`address`) +
            FfiConverterTypeNetworkType.allocationSize(value.`network`) +
            FfiConverterTypeAddressType.allocationSize(value.`addressType`)
    )

    override fun write(value: ValidationResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`address`, buf)
            FfiConverterTypeNetworkType.write(value.`network`, buf)
            FfiConverterTypeAddressType.write(value.`addressType`, buf)
    }
}




enum class AddressError {
    INVALID_ADDRESS,INVALID_NETWORK;
    companion object
}

public object FfiConverterTypeAddressError: FfiConverterRustBuffer<AddressError> {
    override fun read(buf: ByteBuffer) = try {
        AddressError.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AddressError) = 4

    override fun write(value: AddressError, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class AddressType {
    P2PKH,P2SH,P2WPKH,P2WSH,P2TR,UNKNOWN;
    companion object
}

public object FfiConverterTypeAddressType: FfiConverterRustBuffer<AddressType> {
    override fun read(buf: ByteBuffer) = try {
        AddressType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AddressType) = 4

    override fun write(value: AddressType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






sealed class DecodingError {
    object InvalidFormat : DecodingError()
    
    object InvalidNetwork : DecodingError()
    
    object InvalidAmount : DecodingError()
    
    data class InvalidLnurlPayAmount(
        val `amountSatoshis`: ULong, 
        val `min`: ULong, 
        val `max`: ULong
        ) : DecodingError() {
        companion object
    }
    object InvalidTimestamp : DecodingError()
    
    object InvalidChecksum : DecodingError()
    
    object InvalidResponse : DecodingError()
    
    object UnsupportedType : DecodingError()
    
    object InvalidAddress : DecodingError()
    
    object RequestFailed : DecodingError()
    
    object ClientCreationFailed : DecodingError()
    
    data class InvoiceCreationFailed(
        val `message`: String
        ) : DecodingError() {
        companion object
    }
    

    
    companion object
}

public object FfiConverterTypeDecodingError : FfiConverterRustBuffer<DecodingError>{
    override fun read(buf: ByteBuffer): DecodingError {
        return when(buf.getInt()) {
            1 -> DecodingError.InvalidFormat
            2 -> DecodingError.InvalidNetwork
            3 -> DecodingError.InvalidAmount
            4 -> DecodingError.InvalidLnurlPayAmount(
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                )
            5 -> DecodingError.InvalidTimestamp
            6 -> DecodingError.InvalidChecksum
            7 -> DecodingError.InvalidResponse
            8 -> DecodingError.UnsupportedType
            9 -> DecodingError.InvalidAddress
            10 -> DecodingError.RequestFailed
            11 -> DecodingError.ClientCreationFailed
            12 -> DecodingError.InvoiceCreationFailed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: DecodingError) = when(value) {
        is DecodingError.InvalidFormat -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidNetwork -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidAmount -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidLnurlPayAmount -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterULong.allocationSize(value.`amountSatoshis`)
                + FfiConverterULong.allocationSize(value.`min`)
                + FfiConverterULong.allocationSize(value.`max`)
            )
        }
        is DecodingError.InvalidTimestamp -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidChecksum -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidResponse -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.UnsupportedType -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvalidAddress -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.RequestFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.ClientCreationFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is DecodingError.InvoiceCreationFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterString.allocationSize(value.`message`)
            )
        }
    }

    override fun write(value: DecodingError, buf: ByteBuffer) {
        when(value) {
            is DecodingError.InvalidFormat -> {
                buf.putInt(1)
                Unit
            }
            is DecodingError.InvalidNetwork -> {
                buf.putInt(2)
                Unit
            }
            is DecodingError.InvalidAmount -> {
                buf.putInt(3)
                Unit
            }
            is DecodingError.InvalidLnurlPayAmount -> {
                buf.putInt(4)
                FfiConverterULong.write(value.`amountSatoshis`, buf)
                FfiConverterULong.write(value.`min`, buf)
                FfiConverterULong.write(value.`max`, buf)
                Unit
            }
            is DecodingError.InvalidTimestamp -> {
                buf.putInt(5)
                Unit
            }
            is DecodingError.InvalidChecksum -> {
                buf.putInt(6)
                Unit
            }
            is DecodingError.InvalidResponse -> {
                buf.putInt(7)
                Unit
            }
            is DecodingError.UnsupportedType -> {
                buf.putInt(8)
                Unit
            }
            is DecodingError.InvalidAddress -> {
                buf.putInt(9)
                Unit
            }
            is DecodingError.RequestFailed -> {
                buf.putInt(10)
                Unit
            }
            is DecodingError.ClientCreationFailed -> {
                buf.putInt(11)
                Unit
            }
            is DecodingError.InvoiceCreationFailed -> {
                buf.putInt(12)
                FfiConverterString.write(value.`message`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






sealed class LnurlError {
    object InvalidAddress : LnurlError()
    
    object ClientCreationFailed : LnurlError()
    
    object RequestFailed : LnurlError()
    
    object InvalidResponse : LnurlError()
    
    data class InvalidAmount(
        val `amountSatoshis`: ULong, 
        val `min`: ULong, 
        val `max`: ULong
        ) : LnurlError() {
        companion object
    }
    data class InvoiceCreationFailed(
        val `message`: String
        ) : LnurlError() {
        companion object
    }
    

    
    companion object
}

public object FfiConverterTypeLnurlError : FfiConverterRustBuffer<LnurlError>{
    override fun read(buf: ByteBuffer): LnurlError {
        return when(buf.getInt()) {
            1 -> LnurlError.InvalidAddress
            2 -> LnurlError.ClientCreationFailed
            3 -> LnurlError.RequestFailed
            4 -> LnurlError.InvalidResponse
            5 -> LnurlError.InvalidAmount(
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                FfiConverterULong.read(buf),
                )
            6 -> LnurlError.InvoiceCreationFailed(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: LnurlError) = when(value) {
        is LnurlError.InvalidAddress -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is LnurlError.ClientCreationFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is LnurlError.RequestFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is LnurlError.InvalidResponse -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
            )
        }
        is LnurlError.InvalidAmount -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterULong.allocationSize(value.`amountSatoshis`)
                + FfiConverterULong.allocationSize(value.`min`)
                + FfiConverterULong.allocationSize(value.`max`)
            )
        }
        is LnurlError.InvoiceCreationFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterString.allocationSize(value.`message`)
            )
        }
    }

    override fun write(value: LnurlError, buf: ByteBuffer) {
        when(value) {
            is LnurlError.InvalidAddress -> {
                buf.putInt(1)
                Unit
            }
            is LnurlError.ClientCreationFailed -> {
                buf.putInt(2)
                Unit
            }
            is LnurlError.RequestFailed -> {
                buf.putInt(3)
                Unit
            }
            is LnurlError.InvalidResponse -> {
                buf.putInt(4)
                Unit
            }
            is LnurlError.InvalidAmount -> {
                buf.putInt(5)
                FfiConverterULong.write(value.`amountSatoshis`, buf)
                FfiConverterULong.write(value.`min`, buf)
                FfiConverterULong.write(value.`max`, buf)
                Unit
            }
            is LnurlError.InvoiceCreationFailed -> {
                buf.putInt(6)
                FfiConverterString.write(value.`message`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class NetworkType {
    BITCOIN,TESTNET,REGTEST,SIGNET;
    companion object
}

public object FfiConverterTypeNetworkType: FfiConverterRustBuffer<NetworkType> {
    override fun read(buf: ByteBuffer) = try {
        NetworkType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: NetworkType) = 4

    override fun write(value: NetworkType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






sealed class Scanner {
    data class OnChain(
        val `invoice`: OnChainInvoice
        ) : Scanner() {
        companion object
    }
    data class Lightning(
        val `invoice`: LightningInvoice
        ) : Scanner() {
        companion object
    }
    data class PubkyAuth(
        val `auth`: PubkyAuth
        ) : Scanner() {
        companion object
    }
    data class LnurlChannel(
        val `data`: LnurlChannelData
        ) : Scanner() {
        companion object
    }
    data class LnurlAuth(
        val `data`: LnurlAuthData
        ) : Scanner() {
        companion object
    }
    data class LnurlWithdraw(
        val `data`: LnurlWithdrawData
        ) : Scanner() {
        companion object
    }
    data class LnurlAddress(
        val `data`: LnurlAddressData
        ) : Scanner() {
        companion object
    }
    data class LnurlPay(
        val `data`: LnurlPayData
        ) : Scanner() {
        companion object
    }
    data class NodeId(
        val `url`: String, 
        val `network`: NetworkType
        ) : Scanner() {
        companion object
    }
    data class TreasureHunt(
        val `chestId`: String
        ) : Scanner() {
        companion object
    }
    data class OrangeTicket(
        val `ticketId`: String
        ) : Scanner() {
        companion object
    }
    

    
    companion object
}

public object FfiConverterTypeScanner : FfiConverterRustBuffer<Scanner>{
    override fun read(buf: ByteBuffer): Scanner {
        return when(buf.getInt()) {
            1 -> Scanner.OnChain(
                FfiConverterTypeOnChainInvoice.read(buf),
                )
            2 -> Scanner.Lightning(
                FfiConverterTypeLightningInvoice.read(buf),
                )
            3 -> Scanner.PubkyAuth(
                FfiConverterTypePubkyAuth.read(buf),
                )
            4 -> Scanner.LnurlChannel(
                FfiConverterTypeLnurlChannelData.read(buf),
                )
            5 -> Scanner.LnurlAuth(
                FfiConverterTypeLnurlAuthData.read(buf),
                )
            6 -> Scanner.LnurlWithdraw(
                FfiConverterTypeLnurlWithdrawData.read(buf),
                )
            7 -> Scanner.LnurlAddress(
                FfiConverterTypeLnurlAddressData.read(buf),
                )
            8 -> Scanner.LnurlPay(
                FfiConverterTypeLnurlPayData.read(buf),
                )
            9 -> Scanner.NodeId(
                FfiConverterString.read(buf),
                FfiConverterTypeNetworkType.read(buf),
                )
            10 -> Scanner.TreasureHunt(
                FfiConverterString.read(buf),
                )
            11 -> Scanner.OrangeTicket(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: Scanner) = when(value) {
        is Scanner.OnChain -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeOnChainInvoice.allocationSize(value.`invoice`)
            )
        }
        is Scanner.Lightning -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLightningInvoice.allocationSize(value.`invoice`)
            )
        }
        is Scanner.PubkyAuth -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypePubkyAuth.allocationSize(value.`auth`)
            )
        }
        is Scanner.LnurlChannel -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLnurlChannelData.allocationSize(value.`data`)
            )
        }
        is Scanner.LnurlAuth -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLnurlAuthData.allocationSize(value.`data`)
            )
        }
        is Scanner.LnurlWithdraw -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLnurlWithdrawData.allocationSize(value.`data`)
            )
        }
        is Scanner.LnurlAddress -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLnurlAddressData.allocationSize(value.`data`)
            )
        }
        is Scanner.LnurlPay -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterTypeLnurlPayData.allocationSize(value.`data`)
            )
        }
        is Scanner.NodeId -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterString.allocationSize(value.`url`)
                + FfiConverterTypeNetworkType.allocationSize(value.`network`)
            )
        }
        is Scanner.TreasureHunt -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterString.allocationSize(value.`chestId`)
            )
        }
        is Scanner.OrangeTicket -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4
                + FfiConverterString.allocationSize(value.`ticketId`)
            )
        }
    }

    override fun write(value: Scanner, buf: ByteBuffer) {
        when(value) {
            is Scanner.OnChain -> {
                buf.putInt(1)
                FfiConverterTypeOnChainInvoice.write(value.`invoice`, buf)
                Unit
            }
            is Scanner.Lightning -> {
                buf.putInt(2)
                FfiConverterTypeLightningInvoice.write(value.`invoice`, buf)
                Unit
            }
            is Scanner.PubkyAuth -> {
                buf.putInt(3)
                FfiConverterTypePubkyAuth.write(value.`auth`, buf)
                Unit
            }
            is Scanner.LnurlChannel -> {
                buf.putInt(4)
                FfiConverterTypeLnurlChannelData.write(value.`data`, buf)
                Unit
            }
            is Scanner.LnurlAuth -> {
                buf.putInt(5)
                FfiConverterTypeLnurlAuthData.write(value.`data`, buf)
                Unit
            }
            is Scanner.LnurlWithdraw -> {
                buf.putInt(6)
                FfiConverterTypeLnurlWithdrawData.write(value.`data`, buf)
                Unit
            }
            is Scanner.LnurlAddress -> {
                buf.putInt(7)
                FfiConverterTypeLnurlAddressData.write(value.`data`, buf)
                Unit
            }
            is Scanner.LnurlPay -> {
                buf.putInt(8)
                FfiConverterTypeLnurlPayData.write(value.`data`, buf)
                Unit
            }
            is Scanner.NodeId -> {
                buf.putInt(9)
                FfiConverterString.write(value.`url`, buf)
                FfiConverterTypeNetworkType.write(value.`network`, buf)
                Unit
            }
            is Scanner.TreasureHunt -> {
                buf.putInt(10)
                FfiConverterString.write(value.`chestId`, buf)
                Unit
            }
            is Scanner.OrangeTicket -> {
                buf.putInt(11)
                FfiConverterString.write(value.`ticketId`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class Unit {
    BITCOIN,SATOSHI,MILLI_SATOSHI;
    companion object
}

public object FfiConverterTypeUnit: FfiConverterRustBuffer<Unit> {
    override fun read(buf: ByteBuffer) = try {
        Unit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: Unit) = 4

    override fun write(value: Unit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






public object FfiConverterOptionalUInt: FfiConverterRustBuffer<UInt?> {
    override fun read(buf: ByteBuffer): UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: UInt?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




public object FfiConverterOptionalULong: FfiConverterRustBuffer<ULong?> {
    override fun read(buf: ByteBuffer): ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: ULong?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterOptionalByteArray: FfiConverterRustBuffer<ByteArray?> {
    override fun read(buf: ByteBuffer): ByteArray? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterByteArray.read(buf)
    }

    override fun allocationSize(value: ByteArray?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterByteArray.allocationSize(value)
        }
    }

    override fun write(value: ByteArray?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterByteArray.write(value, buf)
        }
    }
}




public object FfiConverterOptionalMapStringString: FfiConverterRustBuffer<Map<String, String>?> {
    override fun read(buf: ByteBuffer): Map<String, String>? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterMapStringString.read(buf)
    }

    override fun allocationSize(value: Map<String, String>?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterMapStringString.allocationSize(value)
        }
    }

    override fun write(value: Map<String, String>?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterMapStringString.write(value, buf)
        }
    }
}



public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<String, String>> {
    override fun read(buf: ByteBuffer): Map<String, String> {
        val len = buf.getInt()
        return buildMap<String, String>(len) {
            repeat(len) {
                val k = FfiConverterString.read(buf)
                val v = FfiConverterString.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<String, String>): Int {
        val spaceForMapSize = 4
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<String, String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}




@Throws(DecodingError::class)

@Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
suspend fun `decode`(`invoice`: String) : Scanner {
    return uniffiRustCallAsync(
        _UniFFILib.INSTANCE.uniffi_bitkitcore_fn_func_decode(FfiConverterString.lower(`invoice`),),
        { future, continuation -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_poll_rust_buffer(future, continuation) },
        { future, continuation -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_complete_rust_buffer(future, continuation) },
        { future -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_free_rust_buffer(future) },
        // lift function
        { FfiConverterTypeScanner.lift(it) },
        // Error FFI converter
        DecodingError.ErrorHandler,
    )
}
@Throws(LnurlError::class)

@Suppress("ASSIGNED_BUT_NEVER_ACCESSED_VARIABLE")
suspend fun `getLnurlInvoice`(`address`: String, `amountSatoshis`: ULong) : String {
    return uniffiRustCallAsync(
        _UniFFILib.INSTANCE.uniffi_bitkitcore_fn_func_get_lnurl_invoice(FfiConverterString.lower(`address`),FfiConverterULong.lower(`amountSatoshis`),),
        { future, continuation -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_poll_rust_buffer(future, continuation) },
        { future, continuation -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_complete_rust_buffer(future, continuation) },
        { future -> _UniFFILib.INSTANCE.ffi_bitkitcore_rust_future_free_rust_buffer(future) },
        // lift function
        { FfiConverterString.lift(it) },
        // Error FFI converter
        LnurlError.ErrorHandler,
    )
}
@Throws(AddressError::class)

fun `validateBitcoinAddress`(`address`: String): ValidationResult {
    return FfiConverterTypeValidationResult.lift(
    rustCallWithError(AddressError) { _status ->
    _UniFFILib.INSTANCE.uniffi_bitkitcore_fn_func_validate_bitcoin_address(FfiConverterString.lower(`address`),_status)
})
}


