[target.armv7-linux-androideabi]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--build-id=sha1",
    "-C", "link-arg=-Wl,-z,max-page-size=16384,-z,common-page-size=16384",
]

[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--build-id=sha1",
    "-C", "link-arg=-Wl,-z,max-page-size=16384,-z,common-page-size=16384",
]

[target.i686-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--build-id=sha1",
    "-C", "link-arg=-Wl,-z,max-page-size=16384,-z,common-page-size=16384",
]

[target.x86_64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
    "-C", "link-arg=-Wl,--build-id=sha1",
    "-C", "link-arg=-Wl,-z,max-page-size=16384,-z,common-page-size=16384",
]

[env]
OPENSSL_STATIC = "1"
OPENSSL_NO_VENDOR = "0"
